imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_pgsql
        host: localhost
        port: 5432
        dbname: doctrine-demo-nantes-test
        user: postgres
        password: DemoNantes44
        charset: UTF8
